### ISSUE TITLE
Error on setup.py

### ISSUE THREAD

**Issue by annak1n** [veryplay/raspi-robot#1]
HI then i try to run setup.py i have this error:

```
root@DevSystem:/opt/dev_shared/raspi-robot# ./setup.py
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied
```

**Comment by veryplay** [comment]
oh , sorry, not write some help info for setup.py, you can see Makefile, which include setup.py usage.

if you are for test on raspi, only execute `cd raspi-robot/raspi_robot/; python robot.py` directly.

 if all is ok after test, can use `make install` raspi-robot to python Library.
